//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaAcademica.CommonValidationDomain.MessageValidations.MessageEntity.MessageAlunos {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageAluno {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageAluno() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibliotecaAcademica.CommonValidationDomain.MessageValidations.MessageEntity.Messa" +
                            "geAlunos.MessageAluno", typeof(MessageAluno).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo CEP do Endereço do Aluno obrigatório..
        /// </summary>
        public static string CepEnderecoIsNullOrEmpty {
            get {
                return ResourceManager.GetString("CepEnderecoIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo CEP do Endereço do Aluno deverá ter 10 caracteres..
        /// </summary>
        public static string CepEnderecoLength {
            get {
                return ResourceManager.GetString("CepEnderecoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao gerar o campo Código de Usuário. Tente outra vez..
        /// </summary>
        public static string CodigoUsuarioIsNullOrEmpty {
            get {
                return ResourceManager.GetString("CodigoUsuarioIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Complemento do Endereço do Aluno fora do intervalo válido de 3 até 150 caracteres..
        /// </summary>
        public static string ComplementoEnderecoLength {
            get {
                return ResourceManager.GetString("ComplementoEnderecoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo DDD do Telefone inválido..
        /// </summary>
        public static string DDDTelefoneLength {
            get {
                return ResourceManager.GetString("DDDTelefoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Email do Aluno inválido..
        /// </summary>
        public static string EmailContains {
            get {
                return ResourceManager.GetString("EmailContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Email do Aluno obrigatório..
        /// </summary>
        public static string EmailIsNullOrEmpty {
            get {
                return ResourceManager.GetString("EmailIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Email do Aluno fora do intervalo válido de 3 até 50 caracteres..
        /// </summary>
        public static string EmailLength {
            get {
                return ResourceManager.GetString("EmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro no sistema ao gerar o campo Id do Aluno. Tente outra vez..
        /// </summary>
        public static string IdAlunoIsNullOrEmpty {
            get {
                return ResourceManager.GetString("IdAlunoIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Logradouro do Endereço do Aluno obrigatório..
        /// </summary>
        public static string LogradouroEnderecoIsNullOrEmpty {
            get {
                return ResourceManager.GetString("LogradouroEnderecoIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Nome do Aluno obrigatório..
        /// </summary>
        public static string NomeIsNullOrEmpty {
            get {
                return ResourceManager.GetString("NomeIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Nome do Aluno fora do interválo válido de 3 até 25 caracteres..
        /// </summary>
        public static string NomeLength {
            get {
                return ResourceManager.GetString("NomeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao gerar o campo Código de Usuário. Tente outra vez..
        /// </summary>
        public static string NovoCodigoUsuarioIsNullOrEmpty {
            get {
                return ResourceManager.GetString("NovoCodigoUsuarioIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Número do Telefone inválido..
        /// </summary>
        public static string NumeroTelefoneLength {
            get {
                return ResourceManager.GetString("NumeroTelefoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Sobrenome do Aluno obrigatório..
        /// </summary>
        public static string SobrenomeIsNullOrEmpty {
            get {
                return ResourceManager.GetString("SobrenomeIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Sobrenome do Aluno fora do intervalo válido de 3 até 50 caracteres..
        /// </summary>
        public static string SobrenomeLength {
            get {
                return ResourceManager.GetString("SobrenomeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Status do Aluno obrigatório..
        /// </summary>
        public static string StatusIsNullOrEmpty {
            get {
                return ResourceManager.GetString("StatusIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Tipo de Usuário obrigatório..
        /// </summary>
        public static string TipoUsuarioIsNullOrEmpty {
            get {
                return ResourceManager.GetString("TipoUsuarioIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Zona do Endereço do Aluno obrigatório..
        /// </summary>
        public static string ZonaEnderecoIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ZonaEnderecoIsNullOrEmpty", resourceCulture);
            }
        }
    }
}
