namespace BibliotecaAcademica.Domain.DomainContextBasic.DomainContext.Enum
{
    public enum Logradouro
    {
        Aeroporto = 1,
        Alameda = 2,
        Área = 3,
        Avenida = 4,
        Campo = 5,
        Chácara = 6,
        Colônia = 7,
        Condomínio = 8,
        Conjunto = 9,
        Distrito = 10,
        Esplanada = 11,
        Estação = 12,
        Estrada = 13,
        Favela = 14,
        Feira = 15,
        Jardim = 16,
        Ladeira = 17,
        Lago = 18,
        Lagoa = 19,
        Largo = 20,
        Loteamento = 21,
        Morro = 22,
        Núcleo = 23,
        Parque = 24,
        Passarela = 25,
        Pátio = 26,
        Praça = 27,
        Quadra = 28,
        Recanto = 29,
        Residencial = 30,
        Rodovia = 31,
        Rua = 32,
        Setor = 33,
        Sítio = 34,
        Travessa = 35,
        Trecho = 36,
        Trevo = 37,
        Vale = 38,
        Vereda = 39,
        Via = 40,
        Viaduto = 41,
        Viela = 42,
        Vila = 43
    }
}